version: '3.8'

services:
  ml-ats-app:
    build: .
    container_name: ml_ats_app
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    restart: unless-stopped