services:
  # Define o Serviço Web principal para a sua aplicação Flask
  - type: web
    name: sistema-selecao-fiap # Você pode mudar este nome
    env: python
    plan: free # Define o plano gratuito do Render
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --timeout 120"
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.9 # Use a versão do Python que você tem localmente
    # Define e conecta o disco persistente a este serviço
    disks:
      - name: dados-persistentes
        mountPath: /app/persistent_data
        sizeGB: 1 # O plano gratuito inclui 1 GB de armazenamento
