services:
  - type: web
    name: sistema-selecao-fiap
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -c gunicorn_config.py app:app"
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.9
