services:
  - type: web
    name: sistema-selecao-fiap
    env: python
    region: frankfurt 
    plan: free
    
    # Comando de construção agora é mais simples e robusto
    buildCommand: "pip install -r requirements.txt"
    
    startCommand: "gunicorn -c gunicorn_config.py app:app"
    healthCheckPath: /health
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.9
