services:
  # Define o Serviço Web principal para a sua aplicação Flask
  - type: web
    name: sistema-selecao
    env: python
    plan: free # Define o plano gratuito do Render
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --timeout 120 app:app"
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.9 # Especifique a versão do Python que você usa
    # Conecta o serviço web ao disco persistente definido abaixo
    disks:
      - name: dados-persistentes
        mountPath: /app/persistent_data
        sizeGB: 1 # O plano gratuito inclui 1 GB de armazenamento

  # Define um Disco Persistente para armazenar seus arquivos
  - type: disk
    name: dados-persistentes
    sizeGB: 1
    plan: free