services:
  - type: web
    name: sistema-selecao-fiap
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --timeout 120"
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.9
    disks:
      - name: dados-persistentes
        mountPath: /app/persistent_data
        sizeGB: 1
